#!/usr/bin/env bash
# Dedup gate + PR create/refresh for the story-status-reconcile workflow.
#
# Extracted from .github/workflows/story-status-reconcile.yml so the gate
# logic can be exercised outside production CI via --dry-run. With --dry-run
# all probes (gh pr list, git ls-remote, git diff) run for real but every
# mutating command (commit, push, pr create) is printed instead of executed.
#
# Required env: BASE_REF, MERGED_PR. Optional: GITHUB_RUN_ID (defaults to
# "local"), GH_TOKEN (required by gh in CI).
#
# Branch strategy — one rolling reconcile PR per base ref:
#   1. An open PR titled "chore: story status reconcile ..." on $BASE_REF →
#      force-push the freshest reconciliation onto its branch; no new PR.
#   2. No open PR, but an orphan chore/status-reconcile-* branch exists on
#      origin (e.g. a previous run was cancelled between push and pr create) →
#      adopt the newest orphan branch and open the PR for it, instead of
#      stranding it forever (the PR-title probe alone never finds branches).
#   3. Neither → fresh branch + new PR.

set -euo pipefail

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
  shift
fi

: "${BASE_REF:?BASE_REF env var required}"
: "${MERGED_PR:?MERGED_PR env var required}"

DATE=$(date +%Y-%m-%d)
RUN_ID="${GITHUB_RUN_ID:-local}"

run() {
  if $DRY_RUN; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

run git config user.name "github-actions[bot]"
run git config user.email "github-actions[bot]@users.noreply.github.com"

# Check if there are actual changes
if git diff --quiet .pHive/epics/; then
  echo "No YAML changes after apply — already current."
  if ! $DRY_RUN; then
    exit 0
  fi
  echo "[dry-run] continuing past empty diff to exercise the gate logic."
fi

# Probe 1 — open reconcile PR already targeting this base ref.
EXISTING_BRANCH=$(gh pr list \
  --state open \
  --base "$BASE_REF" \
  --search 'in:title "story status reconcile"' \
  --json number,headRefName,title \
  --jq '.[] | select(.title | test("^chore: story status reconcile")) | .headRefName' \
  | head -n 1)

if [ -n "$EXISTING_BRANCH" ]; then
  echo "Found open reconcile PR on branch ${EXISTING_BRANCH}; refreshing it."
  BRANCH="$EXISTING_BRANCH"
  run git checkout -B "$BRANCH"
  run git add .pHive/epics/
  run git commit -m "chore: refresh story status reconcile (${DATE}) [skip ci]"
  run git push --force-with-lease origin "$BRANCH"
  echo "Refreshed existing reconcile PR; no new PR opened."
  exit 0
fi

# Probe 2 — orphan reconcile branch with no open PR (a prior run died between
# `git push` and `gh pr create`). Adopt the newest one so it gets its PR
# instead of accumulating as a zombie branch the PR probe never sees.
ORPHAN_BRANCH=$(git ls-remote --heads origin 'chore/status-reconcile-*' \
  | sed 's|.*refs/heads/||' \
  | sort \
  | tail -n 1)

if [ -n "$ORPHAN_BRANCH" ]; then
  echo "Found orphan reconcile branch ${ORPHAN_BRANCH} with no open PR; adopting it."
  BRANCH="$ORPHAN_BRANCH"
  PUSH_ARGS=(--force-with-lease)
else
  BRANCH="chore/status-reconcile-${DATE}-${RUN_ID}"
  PUSH_ARGS=()
fi

run git checkout -B "$BRANCH"
run git add .pHive/epics/
run git commit -m "chore: reconcile stale story status fields (${DATE}) [skip ci]"
run git push "${PUSH_ARGS[@]+"${PUSH_ARGS[@]}"}" origin "$BRANCH"

BODY=$(cat <<EOF
Auto-generated by story-status-reconcile CI workflow after merging #${MERGED_PR}.

Patches story YAML \`status:\` fields that lagged behind episode markers + git state.
This PR is safe to merge directly — it only updates advisory metadata fields.

Generated by \`hive/scripts/story-status-backfill.mjs --apply\`.
EOF
)

run gh pr create \
  --title "chore: story status reconcile ${DATE}" \
  --body "$BODY" \
  --base "$BASE_REF" \
  --head "$BRANCH"
