import assert from 'node:assert/strict';
import http from 'node:http';
import test from 'node:test';

import {
  __resetCache,
  dispatchStoryToAgent,
  ensureIssueBriefMatches,
  moveOutOfBacklogIfNeeded,
  resolveAgentUuidByName,
  serializeStoryBrief,
} from '../hive/lib/multica-story-dispatch/index.mjs';

async function startMockServer(handler) {
  const server = http.createServer(async (req, res) => {
    const chunks = [];
    req.on('data', (chunk) => chunks.push(chunk));
    req.on('end', async () => {
      const rawBody = Buffer.concat(chunks).toString('utf8');
      const body = rawBody ? JSON.parse(rawBody) : null;
      try {
        await handler(req, res, body);
      } catch (error) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: error?.message ?? String(error) }));
      }
    });
  });

  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const { port } = server.address();
  return {
    server,
    serverUrl: `http://127.0.0.1:${port}`,
    close: () => new Promise((resolve) => server.close(resolve)),
  };
}

function sendJson(res, status, body) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

function fullStory(overrides = {}) {
  return {
    id: 'story-1',
    epic: 'epic-1',
    description: '  Ship the story dispatch bridge.',
    acceptance_criteria: ['formats markdown', 'assigns agent'],
    files_to_modify: [
      { file: 'hive/lib/example.mjs', change: 'add helper' },
      { path: 'tests/example.test.mjs', change: 'cover helper' },
    ],
    code_examples: [
      {
        title: 'Call helper',
        file: 'hive/lib/example.mjs',
        language: 'js',
        snippet: 'await dispatchStoryToAgent(serverUrl, token, workspaceId, issueUuid, agentUuid);',
      },
    ],
    references: [
      {
        path: 'hive/lib/multica-bootstrap/index.mjs',
        relevant_excerpt: 'httpJson and cache patterns',
      },
    ],
    ...overrides,
  };
}

test.beforeEach(() => {
  __resetCache();
});

test('AC1 serializeStoryBrief with full story includes all section headings', () => {
  const brief = serializeStoryBrief(fullStory());

  assert.match(brief, /^## Goal/m);
  assert.match(brief, /^## Acceptance Criteria/m);
  assert.match(brief, /^## Files to Touch/m);
  assert.match(brief, /^## Code Examples/m);
  assert.match(brief, /^## References/m);
  assert.match(brief, /Generated by hive multica-story-dispatch/);
});

test('AC2 serializeStoryBrief omits Code Examples when missing', () => {
  const brief = serializeStoryBrief(fullStory({ code_examples: undefined }));

  assert.doesNotMatch(brief, /^## Code Examples/m);
  assert.match(brief, /^## References/m);
});

test('AC3 resolveAgentUuidByName finds existing agent by name', async () => {
  const { serverUrl, close } = await startMockServer((req, res) => {
    assert.equal(req.method, 'GET');
    assert.equal(req.url, '/api/agents?workspace_id=workspace-1');
    assert.equal(req.headers.authorization, 'Bearer mul_test');
    sendJson(res, 200, [{ id: 'agent-uuid-1', name: 'developer' }]);
  });

  try {
    const uuid = await resolveAgentUuidByName(
      serverUrl,
      'mul_test',
      'workspace-1',
      'developer',
    );
    assert.equal(uuid, 'agent-uuid-1');
  } finally {
    await close();
  }
});

test('AC4 resolveAgentUuidByName with empty agents array throws bootstrap hint', async () => {
  const { serverUrl, close } = await startMockServer((req, res) => {
    assert.equal(req.url, '/api/agents?workspace_id=workspace-1');
    sendJson(res, 200, []);
  });

  try {
    await assert.rejects(
      () => resolveAgentUuidByName(serverUrl, 'mul_test', 'workspace-1', 'developer'),
      (error) =>
        error.code === 'BOOTSTRAP_REQUIRED' &&
        error.message.includes('/hive:multica-init'),
    );
  } finally {
    await close();
  }
});

test('AC5 resolveAgentUuidByName with missing name lists available agents', async () => {
  const { serverUrl, close } = await startMockServer((req, res) => {
    assert.equal(req.url, '/api/agents?workspace_id=workspace-1');
    sendJson(res, 200, [
      { id: 'agent-uuid-1', name: 'developer' },
      { id: 'agent-uuid-2', name: 'tester' },
    ]);
  });

  try {
    await assert.rejects(
      () => resolveAgentUuidByName(serverUrl, 'mul_test', 'workspace-1', 'reviewer'),
      (error) =>
        error.code === 'BOOTSTRAP_REQUIRED' &&
        error.message.includes("agent 'reviewer'") &&
        error.message.includes('developer') &&
        error.message.includes('tester'),
    );
  } finally {
    await close();
  }
});

test('AC6 resolveAgentUuidByName caches repeated calls with same args', async () => {
  let getCount = 0;
  const { serverUrl, close } = await startMockServer((req, res) => {
    assert.equal(req.url, '/api/agents?workspace_id=workspace-1');
    getCount += 1;
    sendJson(res, 200, [{ id: 'agent-uuid-1', name: 'developer' }]);
  });

  try {
    const first = await resolveAgentUuidByName(
      `${serverUrl}/`,
      'mul_test',
      'workspace-1',
      'developer',
    );
    const second = await resolveAgentUuidByName(
      serverUrl,
      'mul_test',
      'workspace-1',
      'developer',
    );
    assert.equal(first, 'agent-uuid-1');
    assert.equal(second, 'agent-uuid-1');
    assert.equal(getCount, 1);
  } finally {
    await close();
  }
});

test('AC7 ensureIssueBriefMatches returns unchanged when current matches', async () => {
  const calls = [];
  const { serverUrl, close } = await startMockServer((req, res, body) => {
    calls.push({ method: req.method, url: req.url, body });
    if (req.method === 'GET' && req.url === '/api/issues/issue-1?workspace_id=workspace-1') {
      sendJson(res, 200, { id: 'issue-1', description: 'brief' });
      return;
    }
    sendJson(res, 500, { error: 'unexpected request' });
  });

  try {
    const result = await ensureIssueBriefMatches(
      serverUrl,
      'mul_test',
      'workspace-1',
      'issue-1',
      'brief',
    );
    assert.deepEqual(result, { was_updated: false, current_brief: 'brief' });
    assert.equal(calls.filter((call) => call.method === 'PUT').length, 0);
  } finally {
    await close();
  }
});

test('AC8 ensureIssueBriefMatches updates differing brief with PUT body', async () => {
  const putBodies = [];
  const { serverUrl, close } = await startMockServer((req, res, body) => {
    if (req.method === 'GET' && req.url === '/api/issues/issue-1?workspace_id=workspace-1') {
      sendJson(res, 200, { id: 'issue-1', description: 'old brief' });
      return;
    }
    if (req.method === 'PUT' && req.url === '/api/issues/issue-1?workspace_id=workspace-1') {
      putBodies.push(body);
      sendJson(res, 200, { id: 'issue-1', description: body.description });
      return;
    }
    sendJson(res, 500, { error: 'unexpected request' });
  });

  try {
    const result = await ensureIssueBriefMatches(
      serverUrl,
      'mul_test',
      'workspace-1',
      'issue-1',
      'new brief',
    );
    assert.deepEqual(result, { was_updated: true, current_brief: 'new brief' });
    assert.equal(putBodies.length, 1);
    assert.deepEqual(putBodies[0], { description: 'new brief' });
  } finally {
    await close();
  }
});

test('AC9 dispatchStoryToAgent PUTs agent assignment and returns issue', async () => {
  const putBodies = [];
  const { serverUrl, close } = await startMockServer((req, res, body) => {
    assert.equal(req.method, 'PUT');
    assert.equal(req.url, '/api/issues/issue-1?workspace_id=workspace-1');
    putBodies.push(body);
    sendJson(res, 200, { id: 'issue-1', assignee_type: 'agent', assignee_id: body.assignee_id });
  });

  try {
    const result = await dispatchStoryToAgent(
      serverUrl,
      'mul_test',
      'workspace-1',
      'issue-1',
      'agent-uuid-1',
    );
    assert.deepEqual(putBodies[0], {
      assignee_type: 'agent',
      assignee_id: 'agent-uuid-1',
    });
    assert.equal(result.assignee_id, 'agent-uuid-1');
  } finally {
    await close();
  }
});

test('AC10 moveOutOfBacklogIfNeeded moves backlog and skips in_progress', async () => {
  const putBodies = [];
  const { serverUrl, close } = await startMockServer((req, res, body) => {
    if (req.method === 'GET' && req.url === '/api/issues/backlog-issue?workspace_id=workspace-1') {
      sendJson(res, 200, { id: 'backlog-issue', status: 'backlog' });
      return;
    }
    if (req.method === 'PUT' && req.url === '/api/issues/backlog-issue?workspace_id=workspace-1') {
      putBodies.push(body);
      sendJson(res, 200, { id: 'backlog-issue', status: body.status });
      return;
    }
    if (req.method === 'GET' && req.url === '/api/issues/active-issue?workspace_id=workspace-1') {
      sendJson(res, 200, { id: 'active-issue', status: 'in_progress' });
      return;
    }
    sendJson(res, 500, { error: 'unexpected request' });
  });

  try {
    const moved = await moveOutOfBacklogIfNeeded(
      serverUrl,
      'mul_test',
      'workspace-1',
      'backlog-issue',
    );
    const skipped = await moveOutOfBacklogIfNeeded(
      serverUrl,
      'mul_test',
      'workspace-1',
      'active-issue',
    );
    assert.deepEqual(moved, { was_moved: true });
    assert.deepEqual(skipped, { was_moved: false });
    assert.deepEqual(putBodies, [{ status: 'todo' }]);
  } finally {
    await close();
  }
});
