import assert from 'node:assert/strict';
import test from 'node:test';

import { serializeStoryBrief } from '../index.mjs';

function fullStory(overrides = {}) {
  return {
    id: 'story-1',
    epic: 'epic-1',
    description: '  Ship the story dispatch bridge.',
    acceptance_criteria: ['formats markdown', 'assigns agent'],
    files_to_modify: [
      { file: 'hive/lib/example.mjs', change: 'add helper' },
    ],
    code_examples: [
      {
        title: 'Call helper',
        file: 'hive/lib/example.mjs',
        language: 'js',
        snippet: 'await dispatchStoryToAgent(serverUrl, token, workspaceId, issueUuid, agentUuid);',
      },
    ],
    references: [
      {
        path: 'hive/lib/multica-bootstrap/index.mjs',
        relevant_excerpt: 'httpJson and cache patterns',
      },
    ],
    ...overrides,
  };
}

test('default behavior: omitted options emits no Use /codex:rescue section', () => {
  const brief = serializeStoryBrief(fullStory());
  assert.doesNotMatch(brief, /^## Use \/codex:rescue/m);
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('default behavior: codexInstruction:false emits no Use /codex:rescue section', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: false });
  assert.doesNotMatch(brief, /^## Use \/codex:rescue/m);
  assert.doesNotMatch(brief, /\/codex:rescue/);
});

test('codexInstruction:true emits Use /codex:rescue section between Goal and Acceptance Criteria', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: true });
  assert.match(brief, /^## Use \/codex:rescue/m);
  assert.match(brief, /\/codex:rescue/);

  const goalIdx = brief.indexOf('## Goal');
  const codexIdx = brief.indexOf('## Use /codex:rescue');
  const acIdx = brief.indexOf('## Acceptance Criteria');
  assert.ok(goalIdx >= 0 && codexIdx > goalIdx && acIdx > codexIdx,
    `expected order Goal < Use /codex:rescue < Acceptance Criteria; got ${goalIdx}, ${codexIdx}, ${acIdx}`);
});

test('codexInstruction:true preserves all other brief sections unchanged', () => {
  const brief = serializeStoryBrief(fullStory(), { codexInstruction: true });
  assert.match(brief, /^## Goal/m);
  assert.match(brief, /^## Acceptance Criteria/m);
  assert.match(brief, /^## Files to Touch/m);
  assert.match(brief, /^## Code Examples/m);
  assert.match(brief, /^## References/m);
  assert.match(brief, /Generated by hive multica-story-dispatch/);
});

test('backward-compat: legacy single-arg callers unaffected', () => {
  const briefNoArg = serializeStoryBrief(fullStory());
  const briefEmptyArg = serializeStoryBrief(fullStory(), {});
  assert.equal(briefNoArg, briefEmptyArg);
});
